export const cifi = [
  { attribute: 'perception', label: 'Advertir/Notar', id: 'warn' },
  { attribute: 'dexterity', label: 'Armas a Distancia', id: 'remoteWeapons' },
  { attribute: 'physical', label: 'Armas Cuerpo a Cuerpo', id: 'meleeWeapons' },
  { attribute: 'dexterity', label: 'Artillería', id: 'artillery' },
  { attribute: 'intelligence', label: 'Astrofísica', id: 'astrophysics' },
  { attribute: 'physical', label: 'Atletismo', id: 'athletics' },
  { attribute: 'perception', label: 'Bailar', id: 'dance' },
  { attribute: 'perception', label: 'Buscar', id: 'lookFor' },
  { attribute: 'intelligence', label: 'Callejeo', id: 'callejeo' },
  { attribute: 'intelligence', label: 'Comercio', id: 'trade' },
  { attribute: 'dexterity', label: 'Conducir', id: 'drive' },
  { attribute: 'intelligence', label: 'Criptografía', id: 'cryptography' },
  { attribute: 'dexterity', label: 'Esquivar', id: 'dodge' },
  { attribute: 'intelligence', label: 'Historia', id: 'history' },
  { attribute: 'intelligence', label: 'Idiomas', id: 'languages' },
  { attribute: 'intelligence', label: 'Informática', id: 'computing' },
  { attribute: 'intelligence', label: 'Ingeniería', id: 'engineering' },
  { attribute: 'intelligence', label: 'Leyes', id: 'laws' },
  { attribute: 'intelligence', label: 'Mecánica', id: 'mechanics' },
  { attribute: 'intelligence', label: 'Medicina', id: 'medicine' },
  { attribute: 'perception', label: 'Música', id: 'music' },
  { attribute: 'perception', label: 'Navegación Espacial', id: 'spaceNav' },
  { attribute: 'intelligence', label: 'Ocultismo', id: 'occultism' },
  { attribute: 'perception', label: 'Reflejos', id: 'reflexes' },
  { attribute: 'dexterity', label: 'Pilotar', id: 'pilot' },
  { attribute: 'dexterity', label: 'Sigilo', id: 'stealth' },
  { attribute: 'intelligence', label: 'Supervivencia', id: 'survival' },
] as const
