export const medieval = [
  { attribute: 'perception', label: 'Advertir/Notar', id: 'warn' },
  { attribute: 'dexterity', label: 'Armas a Distancia', id: 'remoteWeapons' },
  { attribute: 'physical', label: 'Armas Cuerpo a Cuerpo', id: 'meleeWeapons' },
  { attribute: 'physical', label: 'Atletismo', id: 'athletics' },
  { attribute: 'perception', label: 'Buscar', id: 'lookFor' },
  { attribute: 'dexterity', label: 'Cabalgar', id: 'ride' },
  { attribute: 'intelligence', label: 'Callejeo', id: 'callejeo' },
  { attribute: 'intelligence', label: 'Comercio', id: 'trade' },
  { attribute: 'perception', label: 'Disfraz', id: 'disguise' },
  { attribute: 'dexterity', label: 'Escalar', id: 'climb' },
  { attribute: 'dexterity', label: 'Esquivar', id: 'dodge' },
  { attribute: 'perception', label: 'Etiqueta', id: 'etiquette' },
  { attribute: 'intelligence', label: 'Fauna', id: 'fauna' },
  { attribute: 'intelligence', label: 'Leyes', id: 'laws' },
  { attribute: 'perception', label: 'Música', id: 'music' },
  { attribute: 'intelligence', label: 'Navegar', id: 'navigate' },
  { attribute: 'dexterity', label: 'Nadar', id: 'swim' },
  { attribute: 'intelligence', label: 'Ocultismo', id: 'occultism' },
  { attribute: 'perception', label: 'Rastrear', id: 'track' },
  { attribute: 'perception', label: 'Reflejos', id: 'reflexes' },
  { attribute: 'intelligence', label: 'Religión', id: 'religion' },
  { attribute: 'dexterity', label: 'Robar bolsillos', id: 'pickpocket' },
  { attribute: 'perception', label: 'Rumores', id: 'rumors' },
  { attribute: 'intelligence', label: 'Sanación/Hierbas', id: 'healing' },
  { attribute: 'dexterity', label: 'Sigilo', id: 'stealth' },
  { attribute: 'intelligence', label: 'Supervivencia/Cazar', id: 'survival' },
  { attribute: 'intelligence', label: 'Tradición/Historia', id: 'history' },
  { attribute: 'dexterity', label: 'Trampas/Cerraduras', id: 'locks' },
] as const
